export enum IconType {
  Cross = 'Cross',
  ArrowLeft = 'ArrowLeft',
  Pause = 'Pause',
  Clock = 'Clock',
  Restart = 'Restart',
  Play = 'Play',
  Alarm = 'Alarm',
  Pen = 'Pen',
  Bicycle = 'Bicycle',
  Note = 'Note',
  Moon = 'Moon',
  Lightbulb = 'Lightbulb',
  Cloud = 'Cloud',
  Lightning = 'Lightning',
  Coin = 'Coin',
  Compass = 'Compass',
  Controller = 'Controller',
  Cup = 'Cup',
  EmojiSmile = 'EmojiSmile',
  Hammer = 'Hammer',
  Headphones = 'Headphones',
  Umbrella = 'Umbrella',
  Wrench = 'Wrench',
  Sun = 'Sun',
}
