import {
  PauseFill,
  XLg,
  ChevronLeft,
  Clock,
  ArrowRepeat,
  PlayFill,
  AlarmFill,
  CloudFill,
  LightbulbFill,
  Bicycle,
  MusicNote,
  LightningFill,
  MoonFill,
  PenFill,
  Coin,
  CompassFill,
  Controller,
  CupFill,
  EmojiSmileFill,
  Hammer,
  Headphones,
  Umbrella,
  Wrench,
  SunFill,
  VolumeMuteFill,
  VolumeUpFill,
} from 'react-bootstrap-icons';

import { IconType } from './IconType';

export const icons: Record<IconType, JSX.Element> = {
  [IconType.Cross]: <XLg viewBox="-0.5 0 16 16" />,
  [IconType.ArrowLeft]: <ChevronLeft viewBox="-0.5 0.5 16 16" />,
  [IconType.Pause]: <PauseFill viewBox="-0.5 0 16 16" />,
  [IconType.Clock]: <Clock viewBox="-0.5 0 16 16" />,
  [IconType.Restart]: <ArrowRepeat viewBox="-0.5 0 16 16" />,
  [IconType.Play]: <PlayFill viewBox="-1 0 16 16" />,
  [IconType.VolumeOff]: <VolumeMuteFill />,
  [IconType.VolumeOn]: <VolumeUpFill />,
  [IconType.Alarm]: <AlarmFill />,
  [IconType.Cloud]: <CloudFill />,
  [IconType.Lightbulb]: <LightbulbFill />,
  [IconType.Bicycle]: <Bicycle />,
  [IconType.Note]: <MusicNote />,
  [IconType.Lightning]: <LightningFill />,
  [IconType.Moon]: <MoonFill />,
  [IconType.Pen]: <PenFill />,
  [IconType.Coin]: <Coin />,
  [IconType.Compass]: <CompassFill />,
  [IconType.Controller]: <Controller />,
  [IconType.Cup]: <CupFill />,
  [IconType.EmojiSmile]: <EmojiSmileFill />,
  [IconType.Hammer]: <Hammer />,
  [IconType.Headphones]: <Headphones />,
  [IconType.Umbrella]: <Umbrella />,
  [IconType.Wrench]: <Wrench />,
  [IconType.Sun]: <SunFill />,
};
